config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :developers, :controllers => { omniauth_callbacks: 'developers/omniauth_callbacks', :registrations => "developers/registrations"}
  
  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  # , :controllers => {omniauth_callbacks: 'clients/omniauth_callbacks', :registrations => "clients/registrations"} 
  
  resources :clients do 
    resources :projects
  end

  resources :projects

  resource :dashboard
  root 'welcome#index' 
  get 'developers/:id' => 'developers#show', as: :developer 
  
  resources :developers do 
    resources :projects
  end


      
  # get "/auth/:provider/callback" => "autentications#create"
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'
  
  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="home-container" alt="mindmap">
  <%= image_tag("mind_map.jpg", alt: "Talent Hacked") %>
  <section>
  <% if developer_signed_in? %>
    <h1 align="center"><%= "Welcome #{current_developer.email}" %></h1>
  <% elsif client_signed_in? %>
    <h1 align="center"><%= "Welcome #{current_client.email}" %></h1>
  <% else %>
    <h1 align="center"><%= "Welcome to Talent Hacked" %></h1>
  <% end %>

  <% if !(current_developer || current_client) %>

    <p align="center">
    <a data-toggle="modal" data-remote="<%=new_client_registration_path%>#modal-edit-fields" data-target="#clientRegisterModal" class="btn btn-primary btn-lg" href='/clients/sign_up'>Clients</a>
    <a data-toggle="modal" data-remote="<%=new_developer_registration_path%>#modal-edit-fields" data-target="#developersRegisterModal" class="btn btn-primary btn-lg" href='/developers/sign_up'>Developers</a>
    </p>
    <% end %>
</div>

<div class="footer">
  <div class="container">
    <p class="text-muted">© Talent Hacked 2014</p>
  </div>
</div>