config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :developers, :controllers => { omniauth_callbacks: 'developers/omniauth_callbacks', :registrations => "developers/registrations"}
  
  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  # , :controllers => {omniauth_callbacks: 'clients/omniauth_callbacks', :registrations => "clients/registrations"} 
  
  resources :clients do 
    resources :projects
  end

  resources :projects

  resource :dashboard
  root 'welcome#index' 
  get 'developers/:id' => 'developers#show', as: :developer 
  
  resources :developers do 
    resources :projects
  end


      
  # get "/auth/:provider/callback" => "autentications#create"
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'
  
  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base

	include Rails.application.routes.url_helpers # neeeded for _path helpers to work in models

	# before_create :save_status
	has_paper_trail

	belongs_to :client
  	has_many :developers, through: :statuses
  	has_many :skills, through: :levels
  	has_many :languages, through: :proficiencies
  	has_many :levels
  	has_many :proficiencies
  	has_many :statuses
    accepts_nested_attributes_for :statuses


	# def save_status
	# 	# status = Status.create
	# 	# status[:project_id] = self.id
	# 	# status.save
	# 	# @project.statuses.first_or_create(:project_id => @project.id)
	# 	 # self.statuses.first_or_create("project_id" => self.id)
	# 	self.status = 'pending'
	# end

	def language_list
		languages.map(&:name).join(',')
	end
	def skill_list
		skills.map(&:name).join(',')
	end

	def skill_list=(list_of_skills)
		skills.clear
		added_skills = list_of_skills.split(',').map(&:strip).uniq.each do |skill_name|
			skills << Skill.find_or_create_by(name: skill_name)
		end
	end

	def dev_match_project (dev_array, project_array)
		match_count = 0
		project_count = project_array.count
		dev_array.each do |skill|
			if project_array.include?(skill)
				match_count += 1
			end
		end
		match_count == project_count
	end

	def viable_developers

		array_of_devs = []

		project_skill_array = []

		self.skills.each do |skill|
			project_skill_array << skill.name	
		end
		Developer.where(verified: true).each do |developer|
			developer_skill_array = []
			developer.skills.each do |skill|
				developer_skill_array << skill.name
			end


			if dev_match_project(developer_skill_array, project_skill_array)
				array_of_devs << developer
			end			
		end

		array_of_devs
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@user = current_client || current_developer

		if params[:status]
			if current_client
				@projects = @user.projects.where(status: params[:status])
			else 
				@projects = @user.statuses.where(status: params[:status]).map(&:project)
			end
		else
			@projects = @user.projects
		end

	
	# @client.projects.each do |project|
		# 	@project_pending if project.status == 'Pending'
		# 	@project_in_progress if project.status == 'In Progress'
		# 	@project_completed if project.status == 'Completed'
		# 	@project_declined if project.status == 'Declined'
		# end

	end

	def new
		@client = Client.find params[:client_id]
		@project = @client.projects.new
	end

	def create
		@client = Client.find params[:client_id]
		skill = params['project'].delete('skills')
		language = params['project'].delete('languages')
		params['project']['status'] = 'Pending'
		@project = @client.projects.create project_params

		added_skills = skill.split(',').map(&:strip).uniq.map do |skill_name|
			Skill.find_or_create_by(name: skill_name)
		end
		added_languages = language.split(',').map(&:strip).uniq.map do |language_name|
			Language.find_or_create_by(name: language_name)
		end
		(@project.languages << added_languages).uniq
		(@project.skills << added_skills).uniq
		dev_array = @project.viable_developers
		dev_array.each do |developer|
			@project.developers << developer
		end
		redirect_to client_project_path(@client, @project)
	end

	def show
		if current_client 
			@client = Client.find params[:client_id]
			@project = @client.projects.find params[:id]
		elsif current_developer
			@developer = Developer.find params[:developer_id]
			@project = @developer.projects.find params[:id]
		end	
	end

	def edit
		if params[:client_id]
			@client = Client.find params[:client_id] 
		else
	 		@developer = Developer.find params[:developer_id]
	 	end
 		@project = Project.find params[:id]
 		@status = @project.statuses.find_by(developer: current_developer)
	end

	def update
		if current_developer
			@project = Project.find(params[:id])
			@status = @project.statuses.find_by(developer: current_developer)

			@status.status = params[:answer] if params[:answer]
			@status.update(status_params) if params[:status]

			@status.save
			if @status.status == 'declined'
				redirect_to developer_projects_path(current_developer)
			elsif params[:status]
				@project.status = "Pending Approval"
				@project.save
				redirect_to dashboard_path
			else 
				# redirect_to new_developer_quote_path(current_developer)
				# redirect_to '/*'
				redirect_to edit_developer_project_path(current_developer, @project)
			end

		elsif current_client
			@client = Client.find params[:client_id] 
			@project = @client.projects.find params[:id]

			skill = params['project'].delete('skills')
			language = params['project'].delete('languages')

	   		@project.update project_params

			added_skills = skill.split(',').map(&:strip).uniq.map do |skill_name|
				Skill.find_or_create_by(name: skill_name)
			end
			added_languages = language.split(',').map(&:strip).uniq.map do |language_name|
				Language.find_or_create_by(name: language_name)
			end
			@project.skills.clear and @project.languages.clear

			(@project.languages << added_languages).uniq
			(@project.skills << added_skills).uniq
	   		redirect_to client_project_path(@client, @project)
		end
	end

	private
	def project_params
		params[:project].permit(:name, :deadline, :client_id, :developer_id, :budget, :projectIndustry, :skills, :description, :status, :timeframe, :workflow, :pitch, :cost)
	end

	def status_params
		params[:status].permit(:cost, :timeframe, :workflow, :pitch, :status)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_show.html.erb
<p><h3>Projects</h3><%= link_to 'Add Project', new_client_project_path(@client.id), class: "btn btn-primary" %></p>
  <% if @client.projects.any? %>
    <% @client.projects.each do |project| %>
      <p><strong>Name:</strong> <%= project.name %></p>
      <p><strong>Deadline:</strong> <%= project.deadline %></p>
      <p><strong>Budget:</strong> <%= number_to_currency(project.budget, :unit => "£") %></p>
      <p><strong>Industry:</strong> <%= project.projectIndustry %></p>
      <p><strong>Description:</strong> <%= project.description %></p>
      <p><strong>Skills:</strong>
        <ul>
           <% if project.skills.any? %>
            <% project.skills.uniq.each do |skill| %>
              <li><%= skill.name %></li>
            <% end %>
          <% else %>
              No skills yet
          <% end %>
        </ul></p>
      <p><strong>Languages:</strong>
        <ul>
           <% if project.languages.any? %>
            <% project.languages.uniq.each do |language| %>
              <li><%= language.name %></li>
            <% end %>
          <% else %>
              No skills yet
          <% end %>
        </ul></p>
      <% end %>
    <% else %>
    <%= 'No projects yet' %> 
  <% end %>

app/views/projects/edit.html.erb
<div id="wrapper">
  <div id="page-wrapper">
  <%= render 'dashboards/sidenav' %>
    <div class="row">
      <div class="col-lg-12">
        <h1><i class="fa fa-laptop"></i> <%= current_developer ? "Quote this" : "Edit the"%> project</h1>
      </div>
    </div><!-- /.row -->

    <div class="row">
      <div class="col-md-offset-2 col-md-8 ">
        <div class="col-sm-12">
            <div class="col-xs-12 col-sm-8">
            	<% if current_developer %>
					<%= form_for @status, url: developer_project_path(current_developer, @project) do |form| %>
						<%= form.hidden_field :status, value: 'pending approval' %>
						
						<p><%= form.label :cost %></p>
						<%= form.text_field :cost %><br>

						<p><%= form.label :timeframe %></p>
						<%= form.text_field :timeframe %><br>

						<p><%= form.label :workflow, 'Explanation of workflow' %></p>
						<%= form.text_area :workflow %><br>

						<p><%= form.label :pitch, 'Pitch (why you)' %></p>
						<%= form.text_area :pitch %><br>

						<%= form.submit %>
					<% end %>
				<% elsif current_client %>
					<%= form_for [@client, @project] do |form| %>
						<div><%= form.label :name %><br>
						<%= form.text_field :name %></div>

						<div><%= form.label :deadline %><br>
						<%= form.text_field :deadline %></div>

						<div><%= form.label :budget, 'Budget (GBP)' %><br>
						<%= form.text_field :budget %></div>

						<div><%= form.label :projectIndustry, 'Industry' %><br>
						<%= form.text_field :projectIndustry %></div>

		                <div><%= form.label :skills %><br>
		                <%= form.text_field :skills, value: @project.skill_list, data: {role: 'tagsinput'} %></div>
                    
		                <div><%= form.label :languages %><br>
		                <%= form.text_field :languages, value: @project.language_list, data: {role: 'tagsinput'} %></div>

						<div><%= form.label :description, 'Description' %><br>
						<%= form.text_area :description %></div>

						<%= form.submit :class => "btn btn-primary" %>
					<% end %>
				<% end %>
			</div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'dashboards/footer' %>

app/views/projects/index.html.erb
<div id="wrapper">
    <div id="page-wrapper">
        <%= render 'dashboards/sidenav' %>
        <% if current_client %>
            <p><h3>Projects</h3><%= link_to 'Add Project', new_client_project_path(@user.id), class: "btn btn-primary" %></p>
            <div class='test-jesus'>
                <% if @projects.any? %>
                    <% @projects.each do |project| %>
                        <div class="project-container col-md-4">
                            <p><strong><%= link_to 'Name:', client_project_path(@user, project) %></strong><%= project.name %></p>
                            <p><%= project.deadline %></p>
                            <p>test</p>
                            <p><strong>Budget:</strong> <%= number_to_currency(project.budget, :unit => "£") %></p>
                            <p><strong>Industry:</strong> <%= project.projectIndustry %></p>
                            <p><strong>Description:</strong> <%= project.description %></p>
                            <p><strong>Status:</strong> <%= project.status %> </p>
                            <p><strong>Skills:</strong></p>
                            <p>
                                <ul>
                                    <% if project.skills.any? %>
                                        <% project.skills.uniq.each do |skill| %>
                                            <li><%= skill.name %></li>
                                        <% end %>
                                    <% else %>
                                        No skills yet
                                    <% end %>
                                </ul>
                            </p>
                            <p><strong>Languages:</strong>
                                <ul>
                                    <% if project.languages.any? %>
                                        <% project.languages.uniq.each do |language| %>
                                            <li><%= language.name %></li>
                                        <% end %>
                                    <% else %>
                                        No skills yet
                                    <% end %>
                                </ul>
                            </p>
                        </div>
                    <% end %>
                <% else %>
                    <%= 'No projects yet' %> 
                <% end %>
            </div>
        <% else %>
            
            <% if @projects.any? %>
              <div class="test-jesus">
              <% @projects.each do |project| %>
              <div class="project-container col-md-4">
                <p><strong><%= link_to 'Name:', developer_project_path(@user, project) %></strong><%= project.name %></p>
                <p><strong>Deadline:</strong> <%= project.deadline %></p>
                <p><strong>Budget:</strong> <%= number_to_currency(project.budget, :unit => "£") %></p>
                <p><strong>Industry:</strong> <%= project.projectIndustry %></p>
                <p><strong>Description:</strong> <%= project.description %></p>
                <p><strong>Status:</strong> <%= project.statuses.where(:project_id => project.id, :developer_id => @user.id).first.status %> </p>
                <p><strong>Skills:</strong>
                  <ul>
                     <% if project.skills.any? %>
                      <% project.skills.uniq.each do |skill| %>
                        <li><%= skill.name %></li>
                      <% end %>
                    <% else %>
                        No skills yet
                    <% end %>
                  </ul></p>
                <p><strong>Languages:</strong>
                  <ul>
                     <% if project.languages.any? %>
                      <% project.languages.uniq.each do |language| %>
                        <li><%= language.name %></li>
                      <% end %>
                    <% else %>
                        No languages yet
                    <% end %>
                  </ul></p>
                   </div> 
                <% end %>
              </div>
              <% else %>
              <%= 'No projects yet' %> 
            <% end %>
          </div>
      <% end %>
  </div>
</div>
<%= render 'dashboards/footer' %>

app/views/projects/new.html.erb
<div id="wrapper">
  <div id="page-wrapper">
  <%= render 'dashboards/sidenav' %>
    <div class="row">
      <div class="col-lg-12">
        <h1><i class="fa fa-laptop"></i> Create a new project</h1>
      </div>
    </div><!-- /.row -->

    <div class="row">
      <div class="col-md-offset-2 col-md-8 ">
        <div class="col-sm-12">
            <div class="col-xs-12 col-sm-8">
								<%= form_for [@client, @project] do |form| %>
								<div><%= form.label :name %><br>
								<%= form.text_field :name %></div>

								<div><%= form.label :deadline %><br>
								<%= form.text_field :deadline %></div>

								<div><%= form.label :budget, 'Budget (GBP)' %><br>
								<%= form.text_field :budget %></div>

								<div><%= form.label :projectIndustry, 'Industry' %><br>
								<%= form.text_field :projectIndustry %></div>

                <div><%= form.label :skills %><br>
                <%= form.text_field :skills, value: "", data: {role: 'tagsinput'} %></div>

                <div><%= form.label :languages %><br>
                <%= form.text_field :languages, value: "", data: {role: 'tagsinput'} %></div>

								<div><%= form.label :description, 'Description' %><br>
								<%= form.text_area :description %></div>

								<%= form.submit :class => "btn btn-primary" %>
							<% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'dashboards/footer' %>

app/views/projects/show.html.erb
<div id="wrapper">
	<div id="page-wrapper">
  		<%= render 'dashboards/sidenav' %>
	  	<div class="test-jesus">	
			<div class="project-list col-md-4">
				<p><strong>Name:</strong><%= @project.name %></p>
				<p><strong>Deadline:</strong> <%= @project.deadline %></p>
				<p><strong>Budget:</strong> <%= number_to_currency(@project.budget, :unit => "£") %></p>
				<p><strong>Industry:</strong> <%= @project.projectIndustry %></p>
				<p><strong>Description:</strong> <%= @project.description %></p>
				<p><strong>Status:</strong> <%= @project.status %> </p>
				<p><strong>Skills:</strong> 
				<ul>
					<% if @project.skills.any? %>
				  		<% @project.skills.uniq.each do |skill| %>
				    		<li><%= skill.name %></li>
				  		<% end %>
					<% else %>
				    	No skills
					<% end %>
				</ul></p>
				<p><strong>Languages:</strong>
				<ul>
					<% if @project.languages.any? %>
				  		<% @project.languages.uniq.each do |language| %>
				    		<li><%= language.name %></li>
						<% end %>
					<% else %>
				    	No languages
					<% end %>

				</ul></p>
				<% if current_developer %>
					<% if @project.statuses.where(:developer_id => current_developer.id, :project_id => @project.id).first.status == 'pending' %>
						<%= link_to 'Accept', project_path(@project, answer: 'pending_approval'), method: :patch %>
	   					<%= link_to 'Decline', project_path(@project, answer: 'declined'), method: :patch %>
	   				<% end %>
	   			<% else %>
	   				<%= link_to 'Edit Project', edit_client_project_path(current_client, @project), class: "btn btn-primary" %>
	   			<% end %>
			</div>	
		</div>
	</div>
</div>


<%= render 'dashboards/footer' %>