config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :developers, :controllers => { omniauth_callbacks: 'developers/omniauth_callbacks', :registrations => "developers/registrations"}
  
  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  # , :controllers => {omniauth_callbacks: 'clients/omniauth_callbacks', :registrations => "clients/registrations"} 
  
  resources :clients do 
    resources :projects
  end

  resources :projects

  resource :dashboard
  root 'welcome#index' 
  get 'developers/:id' => 'developers#show', as: :developer 
  
  resources :developers do 
    resources :projects
  end


      
  # get "/auth/:provider/callback" => "autentications#create"
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'
  
  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @client = current_client
    @developer = current_developer
  end
  
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/dashboards/_sidenav.html.erb
<!-- Sidebar -->
<nav class="navbar navbar-inverse">
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <% if current_client %>
      <ul class="nav navbar-nav side-nav">
        <li><%= link_to "<i class='fa fa-dashboard'></i> Dashboard".html_safe, dashboard_path %></li>
        <li><%= link_to "<i class='fa fa-file-text'></i> New Project".html_safe, new_client_project_path(current_client) %></li>
        <li><%= link_to "<i class='fa fa-desktop'></i> Pending Quotation".html_safe, client_projects_path(current_client, status: 'Pending') %></li>
        <li><%= link_to "<i class='fa fa-reply-all'></i> Pending Approval".html_safe, client_projects_path(current_client, status: 'Pending Approval') %></li>
        <li><%= link_to "<i class='fa fa-tasks'></i> Confirmed".html_safe, client_projects_path(current_client, status: 'Confirmed') %></li>
        <li><%= link_to "<i class='fa fa-check-square-o'></i> Completed".html_safe, client_projects_path(current_client, status: 'Completed') %></li>
        <li><%= link_to "<i class='fa fa-exclamation-circle'></i> Declined".html_safe, client_projects_path(current_client, status: 'Declined') %></li>
      </ul>
    <% elsif current_developer %>
      <ul class="nav navbar-nav side-nav">
        <li><%= link_to "<i class='fa fa-dashboard'></i> Dashboard".html_safe, dashboard_path %></li>
        <li><%= link_to "<i class='fa fa-desktop'></i> Pending Quotation".html_safe, developer_projects_path(current_developer, status: 'pending') %></li>
        <li><%= link_to "<i class='fa fa-reply-all'></i> Pending Approval".html_safe, developer_projects_path(current_developer, status: 'pending approval') %></li>
        <li><%= link_to "<i class='fa fa-tasks'></i> Confirmed".html_safe, developer_projects_path(current_developer, status: 'confirmed') %></li>
        <li><%= link_to "<i class='fa fa-check-square-o'></i> Completed".html_safe, developer_projects_path(current_developer, status: 'completed') %></li>
        <li><%= link_to "<i class='fa fa-exclamation-circle'></i> Declined".html_safe, developer_projects_path(current_developer, status: 'declined') %></li>
      </ul>
    <% end %>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/dashboards/show.html.erb
<div id="wrapper">
  <div id="page-wrapper">
    <%= render 'dashboards/sidenav' %>
    <div class="row">
      <div class="col-lg-12">
        <h1><i class="fa fa-dashboard"></i> Dashboard <small>Statistics Overview</small></h1>
      </div>
    </div><!-- /.row -->

    <% if current_client %>
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-info test-jesus">
          <div class="panel-heading offers">
            <div class="row">
              <div class='col-xs-6'>
                <%= link_to "<i class='fa fa-file-text fa-5x'></i>".html_safe, new_client_project_path(current_client), method: :get %>
              </div>
              <div class="col-xs-6 text-right">
                <p class="announcement-heading">New Project</p>
                <p class="announcement-text"></p>
              </div>
            </div>
          </div>       
        </div>
      </div>
    </div> <!-- create a new project -->
    <% end %>

      <div class="col-lg-12">
        <div class="panel panel-info test-jesus">
          <div class="panel-heading pending offers">
            <div class="row">
              <div class="col-xs-6">
                <% if current_client %> 
                  <%= link_to "<i class='fa fa-desktop fa-5x'></i>".html_safe, client_projects_path(@client, status: 'Pending'), method: :get, class: "col-xs-6" %>
                <% else %>
                   <%= link_to "<i class='fa fa-desktop fa-5x'></i>".html_safe, developer_projects_path(@developer, status: 'pending'), method: :get, class: "col-xs-6" %>
                <% end %>
              </div>
              <div class="col-xs-6 text-right">
                <p class="announcement-heading">
                <% if current_client %>             
                  <%= @client.projects.select{|project| project.status == 'Pending'}.count %></p>
                  <p class="announcement-text">Pending Quotation</p>
                <% else %>
                  <%= @developer.projects.select{|project| project.statuses.where(:project_id => project.id, :developer_id => @developer.id).first.status == 'pending'}.count %></p>
                  <p class="announcement-text">Pending Quotation</p>
                <% end %>
              </div>
            </div>
          </div>       
        </div>
      </div>

      <div class="col-lg-12">
        <div class="panel panel-info test-jesus">
          <div class="panel-heading pending offers">
            <div class="row">
              <div class="col-xs-6">
                <% if current_client %> 
                  <%= link_to "<i class='fa fa-reply-all fa-5x'></i>".html_safe, client_projects_path(@client, status: 'Pending Approval'), method: :get, class: "col-xs-6" %>
                  <% else %>
                   <%= link_to "<i class='fa fa-reply-all fa-5x'></i>".html_safe, developer_projects_path(@developer, status: 'pending approval'), method: :get, class: "col-xs-6" %>
                  <% end %>
              </div>
              <div class="col-xs-6 text-right">
                <p class="announcement-heading">
                <% if current_client %>             
                  <%= @client.projects.select{|project| project.status == 'Pending Approval'}.count %></p>
                  <p class="announcement-text">Pending Approval</p>
                <% else %>
                  <%= @developer.projects.select{|project| project.statuses.where(:project_id => project.id, :developer_id => @developer.id).first.status == 'pending approval' }.count %></p>
                  <p class="announcement-text">Pending Approval</p>
                <% end %>
                
              </div>
            </div>
          </div>       
        </div>
      </div>

      <div class="col-lg-12">
        <div class="panel panel-info test-jesus">
          <div class="panel-heading pending offers">
            <div class="row">
              <div class="col-xs-6">
                <% if current_client %> 
                  <%= link_to "<i class='fa fa-tasks fa-5x'></i>".html_safe, client_projects_path(@client, status: 'Confirmed'), method: :get, class: "col-xs-6" %>
                  <% else %>
                   <%= link_to "<i class='fa fa-tasks fa-5x'></i>".html_safe, developer_projects_path(@developer, status: 'confirmed'), method: :get, class: "col-xs-6" %>
                  <% end %>
              </div>
              <div class="col-xs-6 text-right">
                <p class="announcement-heading">
                <% if current_client %>             
                  <%= @client.projects.select{|project| project.status == 'Confirmed'}.count %></p>
                <% else %>
                  <%= @developer.projects.select{|project| project.statuses.where(:project_id => project.id, :developer_id => @developer.id).first.status == 'confirmed' }.count %></p>
                <% end %>
                <p class="announcement-text">Confirmed</p>
              </div>
            </div>
          </div>       
        </div>
      </div>

      <div class="col-lg-12">
        <div class="panel panel-info test-jesus">
          <div class="panel-heading pending offers">
            <div class="row">
              <div class="col-xs-6">
                <% if current_client %> 
                  <%= link_to "<i class='fa fa-check-square-o fa-5x'></i>".html_safe, client_projects_path(@client, status: 'Completed'), method: :get, class: "col-xs-6" %>
                  <% else %>
                   <%= link_to "<i class='fa fa-check-square-o fa-5x'></i>".html_safe, developer_projects_path(@developer, status: 'completed'), method: :get, class: "col-xs-6" %>
                  <% end %>
              </div>
              <div class="col-xs-6 text-right">
                <p class="announcement-heading">
                <% if current_client %>             
                  <%= @client.projects.select{|project| project.status == 'Completed'}.count %></p>
                <% else %>
                  <%= @developer.projects.select{|project| project.statuses.where(:project_id => project.id, :developer_id => @developer.id).first.status == 'completed' }.count %></p>
                <% end %>
                <p class="announcement-text">Completed</p>
              </div>
            </div>
          </div>       
        </div>
      </div>

      <div class="col-lg-12">
        <div class="panel panel-info test-jesus">
          <div class="panel-heading pending offers">
            <div class="row">
              <div class="col-xs-6">
                <% if current_client %> 
                  <%= link_to "<i class='fa fa-exclamation-circle fa-5x'></i>".html_safe, client_projects_path(@client, status: 'Declined'), method: :get, class: "col-xs-6" %>
                  <% else %>
                   <%= link_to "<i class='fa fa-exclamation-circle fa-5x'></i>".html_safe, developer_projects_path(@developer, status: 'declined'), method: :get, class: "col-xs-6" %>
                  <% end %>
              </div>
              <div class="col-xs-6 text-right">
                  <p class="announcement-heading">
                <% if current_client %>             
                  <%= @client.projects.select{|project| project.status == 'Declined'}.count %></p>
                <% else %>
                  <%= @developer.projects.select{|project| project.statuses.where(:project_id => project.id, :developer_id => @developer.id).first.status == 'declined' }.count %></p>
                <% end %>
                <p class="announcement-text">Declined</p>
              </div>
            </div>
          </div>       
        </div>
      </div>

  </div><!-- /#page-wrapper -->
</div><!-- /#wrapper -->