config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :developers, :controllers => { omniauth_callbacks: 'developers/omniauth_callbacks', :registrations => "developers/registrations"}
  
  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  # , :controllers => {omniauth_callbacks: 'clients/omniauth_callbacks', :registrations => "clients/registrations"} 
  
  resources :clients do 
    resources :projects
  end

  resources :projects

  resource :dashboard
  root 'welcome#index' 
  get 'developers/:id' => 'developers#show', as: :developer 
  
  resources :developers do 
    resources :projects
  end


      
  # get "/auth/:provider/callback" => "autentications#create"
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'
  
  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_header.html.erb
<!-- Header -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div id="logo-image">
      <%= link_to image_tag("talent_hacked_italic_swoosh_white.png", alt: "Talent Hacked"), '/' %>
    </div>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">

    <ul class="nav navbar-nav navbar-right navbar-user">
      <li class="dropdown user-dropdown">
        <% if current_developer %>
          <%= link_to "<i class='fa fa-user'></i> #{current_developer.email} <i class='fa fa-chevron-down'></i>".html_safe, dashboard_path, class: "dropdown-toggle", :data => {:toggle => "dropdown"} %>
          <ul class="dropdown-menu">
            <li><%= link_to "<i class='fa fa-dashboard'></i> Dashboard".html_safe, dashboard_path, method: :get %></li>
            <li><%= link_to "<i class='fa fa-align-justify'></i> Show profile".html_safe, developer_path(current_developer.id) %></li>
            <li><%= link_to "<i class='fa fa-gear'></i> Edit profile".html_safe, edit_developer_registration_path, method: :get %></li>
            <li class="divider"></li>
            <li><%= link_to "<i class='fa fa-power-off'></i> Sign out".html_safe, destroy_developer_session_path, method: :delete %></li>
          </ul>
        <% elsif current_client %>
          <%= link_to "<i class='fa fa-user'></i> #{current_client.email} <i class='fa fa-chevron-down'></i>".html_safe, dashboard_path, class: "dropdown-toggle", :data => {:toggle => "dropdown"} %>
          <ul class="dropdown-menu">
            <li><%= link_to "<i class='fa fa-dashboard'></i> Dashboard".html_safe, dashboard_path, method: :get %></li>
            <li><%= link_to "<i class='fa fa-align-justify'></i> Show profile".html_safe, client_path(current_client.id) %></li>
            <li><%= link_to "<i class='fa fa-gear'></i> Edit profile".html_safe, edit_client_registration_path, method: :get %></li>
            <li class="divider"></li>
            <li><%= link_to "<i class='fa fa-power-off'></i> Sign out".html_safe, destroy_client_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <%= link_to "Have an account? <i class='fa fa-chevron-down'></i>".html_safe, dashboard_path, class: "dropdown-toggle", :data => {:toggle => "dropdown"} %>
          <ul class="dropdown-menu">
            <li><a data-toggle="modal" data-remote="<%=new_developer_session_path%>#modal-edit-fields" data-target="#developersLoginModal" href='/developers/sign_in'>Developer Sign in</a></li>
            <li><%= link_to "Developer Sign in with LinkedIn", developer_omniauth_authorize_path(:linkedin) %></li>
            <li class="divider"></li>

            <li><a data-toggle="modal" data-remote="<%=new_client_session_path%>#modal-edit-fields" data-target="#clientLoginModal" href='/clients/sign_in'>Client Sign in</a></li>
            <li class="divider"></li>
            <li><%= link_to "Admin Sign in", admin_root_path %></li>
          </ul>
        <% end %>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>TalentHacked</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'dashboards', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
	</head>
	<body>
    <%= content_tag(:p, notice, id: 'notice') if notice %>
    <%= content_tag(:p, alert,  id: 'alert') if alert  %>
    <%= render 'dashboards/shim' %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <!-- Modal -->

<% ["developersLoginModal", "clientLoginModal", "developersRegisterModal", "clientRegisterModal"].each do |modal_id| %>
  <div class="modal fade" id="<%= modal_id %>" tabindex="-1" role="dialog" aria-labelledby="developersModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                   <h4 class="modal-title">Modal title</h4>

              </div>
              <div class="modal-body"><div class="te"></div></div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
              </div>
          </div>
          <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
  </div>
<% end %>
<!-- /.modal -->
  </body>
</html>